postgres:
  host: ${POSTGRES_HOST:localhost:5432}
rabbitmq:
  host: ${RABBITMQ_HOST:localhost:5672}

spring:
  datasource:
    url: jdbc:postgresql://${postgres.host}/messaging_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: ${rabbitmq.host}
    port: 5672
    username: guest
    password: guest

server:
  error:
    include-message: always
  port: 8081

messaging:
  rabbitmq:
    queue: message
    exchange: messageExchange
    routing-key: messageRoutingKey